name: Run bot in background

on:
  push:
    branches:
      - main

jobs:
  run_background_process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Start bot background process
        run: |
          nohup ./bot.py > output.log 2>&1 &
