name: Run bot in background

on:
  push:
    branches:
      - main

jobs:
  example_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: pip install discord.py
      
      - name: Run Python script with secret
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python bot.py

