name: Run bot in background

on:
  push:
    branches: [main , sora ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
       pip install discord.py
       pip install python-dotenv
      
    - name: Run Python script with secret
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: timeout 60s python bot.py

